services:
  app:
    container_name: app
    build: .
    restart: always
    environment:
      SECRET: ${SECRET}

      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SECURE: ${MINIO_SECURE}
      DOCUMENT_BUCKET: ${DOCUMENT_BUCKET}
    ports:
      - "$PORT:8080"
    volumes:
      - .db:/app/.db

  minio:
    image: minio/minio:RELEASE.2024-06-11T03-13-30Z-cpuv1
    command: server --console-address ":9001" /data/
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "$MINIO_PORT:9000"
      - "$MINIO_CONSOLE_PORT:9001"
    volumes:
      - .data:/data

