// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: competition.sql

package sqlc

import (
	"context"
	"time"
)

const createCompetition = `-- name: CreateCompetition :one
INSERT INTO
    competitions (trainer_id, name, description, tours, age, size, closes_at)
VALUES
    (?, ?, ?, ?, ?, ?, ?) RETURNING id, trainer_id, name, description, tours, age, size, closes_at, created_at
`

type CreateCompetitionParams struct {
	TrainerID   int64
	Name        string
	Description string
	Tours       int64
	Age         int64
	Size        int64
	ClosesAt    time.Time
}

func (q *Queries) CreateCompetition(ctx context.Context, arg CreateCompetitionParams) (Competition, error) {
	row := q.db.QueryRowContext(ctx, createCompetition,
		arg.TrainerID,
		arg.Name,
		arg.Description,
		arg.Tours,
		arg.Age,
		arg.Size,
		arg.ClosesAt,
	)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.Name,
		&i.Description,
		&i.Tours,
		&i.Age,
		&i.Size,
		&i.ClosesAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCompetitionDay = `-- name: CreateCompetitionDay :one
INSERT INTO
    competition_days (competition_id, date, start_time, end_time)
VALUES
    (?, ?, ?, ?) RETURNING competition_id, date, start_time, end_time
`

type CreateCompetitionDayParams struct {
	CompetitionID int64
	Date          time.Time
	StartTime     time.Time
	EndTime       time.Time
}

func (q *Queries) CreateCompetitionDay(ctx context.Context, arg CreateCompetitionDayParams) (CompetitionDay, error) {
	row := q.db.QueryRowContext(ctx, createCompetitionDay,
		arg.CompetitionID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
	)
	var i CompetitionDay
	err := row.Scan(
		&i.CompetitionID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteCompetition = `-- name: DeleteCompetition :exec
DELETE FROM
    competitions
WHERE
    id = ?
`

func (q *Queries) DeleteCompetition(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCompetition, id)
	return err
}

const getCompetition = `-- name: GetCompetition :one
SELECT
    competitions.id, competitions.trainer_id, competitions.name, competitions.description, competitions.tours, competitions.age, competitions.size, competitions.closes_at, competitions.created_at,
    users.id, users.role_id, users.email, users.password, users.first_name, users.last_name, users.middle_name, users.created_at
FROM
    competitions
    JOIN users ON users.id = competitions.trainer_id
WHERE
    competitions.id = ?
LIMIT
    1
`

type GetCompetitionRow struct {
	Competition Competition
	User        User
}

func (q *Queries) GetCompetition(ctx context.Context, id int64) (GetCompetitionRow, error) {
	row := q.db.QueryRowContext(ctx, getCompetition, id)
	var i GetCompetitionRow
	err := row.Scan(
		&i.Competition.ID,
		&i.Competition.TrainerID,
		&i.Competition.Name,
		&i.Competition.Description,
		&i.Competition.Tours,
		&i.Competition.Age,
		&i.Competition.Size,
		&i.Competition.ClosesAt,
		&i.Competition.CreatedAt,
		&i.User.ID,
		&i.User.RoleID,
		&i.User.Email,
		&i.User.Password,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.MiddleName,
		&i.User.CreatedAt,
	)
	return i, err
}

const getCompetitionDays = `-- name: GetCompetitionDays :many
SELECT
    competition_id, date, start_time, end_time
FROM
    competition_days
WHERE
    competition_id = ?
ORDER BY date
`

func (q *Queries) GetCompetitionDays(ctx context.Context, competitionID int64) ([]CompetitionDay, error) {
	rows, err := q.db.QueryContext(ctx, getCompetitionDays, competitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitionDay
	for rows.Next() {
		var i CompetitionDay
		if err := rows.Scan(
			&i.CompetitionID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitions = `-- name: ListCompetitions :many
SELECT
    users.id, users.role_id, users.email, users.password, users.first_name, users.last_name, users.middle_name, users.created_at,
    competitions.id, competitions.trainer_id, competitions.name, competitions.description, competitions.tours, competitions.age, competitions.size, competitions.closes_at, competitions.created_at,
    COUNT() OVER() as total
FROM
    competitions
    JOIN users ON users.id = competitions.trainer_id
LIMIT
    ? OFFSET ?
`

type ListCompetitionsParams struct {
	Limit  int64
	Offset int64
}

type ListCompetitionsRow struct {
	User        User
	Competition Competition
	Total       int64
}

func (q *Queries) ListCompetitions(ctx context.Context, arg ListCompetitionsParams) ([]ListCompetitionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompetitions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionsRow
	for rows.Next() {
		var i ListCompetitionsRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.RoleID,
			&i.User.Email,
			&i.User.Password,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.MiddleName,
			&i.User.CreatedAt,
			&i.Competition.ID,
			&i.Competition.TrainerID,
			&i.Competition.Name,
			&i.Competition.Description,
			&i.Competition.Tours,
			&i.Competition.Age,
			&i.Competition.Size,
			&i.Competition.ClosesAt,
			&i.Competition.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitionsByTrainer = `-- name: ListCompetitionsByTrainer :many
SELECT
    id, trainer_id, name, description, tours, age, size, closes_at, created_at
FROM
    competitions
WHERE
    trainer_id = ?
LIMIT
    ? OFFSET ?
`

type ListCompetitionsByTrainerParams struct {
	TrainerID int64
	Limit     int64
	Offset    int64
}

func (q *Queries) ListCompetitionsByTrainer(ctx context.Context, arg ListCompetitionsByTrainerParams) ([]Competition, error) {
	rows, err := q.db.QueryContext(ctx, listCompetitionsByTrainer, arg.TrainerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Competition
	for rows.Next() {
		var i Competition
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.Name,
			&i.Description,
			&i.Tours,
			&i.Age,
			&i.Size,
			&i.ClosesAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompetition = `-- name: UpdateCompetition :exec
UPDATE
    competitions
SET
    name = coalesce(?1, name),
    description = coalesce(?2, description),
    closes_at = coalesce(?3, closes_at)
    -- more?
WHERE
    id = ?4
`

type UpdateCompetitionParams struct {
	Name        *string
	Description *string
	ClosesAt    *time.Time
	ID          int64
}

func (q *Queries) UpdateCompetition(ctx context.Context, arg UpdateCompetitionParams) error {
	_, err := q.db.ExecContext(ctx, updateCompetition,
		arg.Name,
		arg.Description,
		arg.ClosesAt,
		arg.ID,
	)
	return err
}
