// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Competition struct {
	ID          int64
	Name        string
	Description string
	StartDate   time.Time
	TrainerID   int64
}

type User struct {
	ID        int64
	Name      string
	Email     string
	Password  string
	IsTrainer bool
	BirthDate *time.Time
}
